version: '2git init'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: docker_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "33060:3306"